name: Scoreboard
version: 1.0.1
api: 2.0.0
authors: [Buddelbubi]
description: Add a scoreboard to your PowerNukkitX server.
main: org.powernukkitx.scoreboard.Scoreboard
softdepend:
  - PlaceholderAPI
